### ISSUE TITLE
Setting fan speed via Siri returns nonsense 

### ISSUE THREAD

**Issue by vdotn** [aarons22/homebridge-bond#32] opened 2019-10-01 11:43 UTC
Running plugin 2.1.0, with phone on iOS 13.1.2. 

Saying the command “turn on the ....room fan to 66” (or medium in my case for a 3 speed fan) results in Siri saying ok I’ve set the fan speed to 3, and turning the fan to 100%

**Expected behavior**
Siri confirms the fan speed correctly and sets the fan to the desired speed. 

**Screenshots**
![AAB8BD87-A683-4C9B-A839-B5F70E224620](https://user-images.githubusercontent.com/36348492/65958822-5b189400-e41e-11e9-85df-bdedb2a3e1bd.png)
![9251C677-A157-4D96-90A5-D7D8BE8A2E36](https://user-images.githubusercontent.com/36348492/65958823-5b189400-e41e-11e9-82d4-ffb86033c914.png)

**Additional context**
I suspect what’s happening here is a mismatch of units in the workflow, since Siri/HomeKit expects fan speed in a 0-100 range, while the bond expects fan speed in a 0-originating array that increments by 1. 

So with the Siri command:
HomeKit tells bond plugin set the fan speed to 66 -> plugin rounds it to the highest value supported by the bond for this particular fan (3 in this case), and tells the bond to make fan speed 3, which is dutifully does, and the fan ramps up to highest. Then the callback fires without converting bond values to HomeKit values and returns 3, so Siri happily reads back that it’s set the fan speed to 3.

**Comment by aarons22** [comment] 2019-10-01 15:45
Dang, I was hoping using `setProps` would allow me to use a different unit. I'll take a look

**Comment by vdotn** [comment] 2019-10-01 18:32
Yeah; unfortunately the v1 setProps statically took 0/33/66/99 as static values so everything went swimmingly there (although there was some off-by-one stuff, you’d tell Siri to set fan to 100 and it’d say ok great I set it to 99). You converted it to the array that dynamically populated with the number of speeds 0-7 (which is a huge feature win btw!)

I’m also not sure how Apple slices up the speed bar in the home app, if they use a simple divide 100/numSpeeds and then floor/ceiling it, or try to do something more clever. You may also end up with off-by-one on the Siri voice response in some instances but it’s still better than off-by-sixty 😁😁

**Comment by aarons22** [comment] 2019-10-02 19:24
Should be fixed in 2.1.3. Can you confirm?

**Comment by vdotn** [comment] 2019-10-02 21:34
Better, but still bugged. I’ll do a better write up when I get home. Basically “Siri set the fan to 33” -> Siri goes “ok I’ve set it to 32” -> actually sets it to 17 which is the next value down from 33.

**Comment by aarons22** [comment] 2019-10-03 01:44
How many speeds do you have? Also, can you add `"debug": true` to your config and look for the line that reports the min step and max value?

I think part of the issue is how Siri is interpreting the request, but I also feel like the verbal response from Siri vs what's shown in HomeKit is a bit misleading. Siri seems to _always_ respond in the increments of the minStep value. For me, I've got three speeds, so the possible responses when requesting a percentage are:
"OK, I set the Living Room Fan to [0%, 33%, 66%, 99%]"
- Asking for "low" == 33%, "medium" == 66%, "high" = 99%

If I ask for a raw number (i.e. "set the living room fan to 22%"), it will round to the nearest step correctly (in that example, it goes to 33, but asking for 15% goes to 0).

Setting aside Siri for a second, in HomeKit, the slider snaps in at 33%, 67% and 100%, so it's possible I need to adjust some rounding on my end to ensure the snaping matches up with what Siri is responding with. I'm taking the floor of the calculated step because it won't let me provide decimals.

**Comment by vdotn** [comment] 2019-10-07 14:43
Apologies I’ll do some debugging tonight. Weekend was crazy busy. It seems like there’s also something going on with how the response to getFanSpeedValue is being interpreted by HomeKit.

Example (on a 6-speed fan): set speed to 67% either by Siri or in home app. Switch apps to something else, then back to home so values refresh. Speed will now read 50%. However in the Bond app the speed is on 4 which should translate to 67% in HomeKit. I’m guessing this is related to more rounding foolishness.

Again I’ll do my best to make time tonight to run some more thorough testing and find more failure cases. I’m hopeful these will be easily squash-able!

**Comment by iRayanKhan** [comment] 2019-10-07 16:48
Can you change the speed via shortcuts? I wonder if it is a speed # related issue dealing with this issue and #35

**Comment by vdotn** [comment] 2019-10-08 19:19
Haven’t tried but I’ll give it a test later.

**Comment by twentyNoise** [comment] 2019-10-11 04:49
I noticed this as well and at first I didn't like it. But to be honest it's much easier to say "set the fan speed to 4%" If I want speed 4, or 3% for speed three. Just easier then remembering the different splits... not that there are many or that they're hard to remember, but just just keeps things simple." 

What would be best is if you can say "set fan to speed 4" and Siri can respond with OK I set the fan to Speed 4" and just forget all the percentages. I wish Apple would change the Fan control to be in 'speeds' or notches rather than percentages. I don't know of any fans that can be set to parts of a percentage.

**Comment by aarons22** [comment] 2019-10-17 15:49
I've seen some inconsistency on my end as well. I'll take a look!

**Comment by aarons22** [comment] 2019-10-18 00:48
Found the issue where you can't get fan speed above 67%. It's fixed in [2.3.2](https://github.com/aarons22/homebridge-bond/releases/tag/2.3.2)!

**Comment by vdotn** [comment] 2019-10-18 02:58
The slider now shows correct values, probably Apple is doing some rounding and guessing to help out.

However the raw values are still off, which also affects Siri because it reads back the raw values as opposed to the value as interpreted by the Home app. I went through all the speeds on my 6-speed fan and the raw values are off as follows:

```
[10/17/2019, 10:52:51 PM] [Bond] value changed: true
[10/17/2019, 10:52:51 PM] [Bond] value changed: 16 # Should be 17
[10/17/2019, 10:52:57 PM] [Bond] value changed: 32 # Should be 33
[10/17/2019, 10:52:59 PM] [Bond] value changed: 48 # Should be 50
[10/17/2019, 10:53:00 PM] [Bond] value changed: 64 # Should be 66
[10/17/2019, 10:53:01 PM] [Bond] value changed: 80 # Should be 83
[10/17/2019, 10:53:02 PM] [Bond] value changed: 96 # Should be 100
```

**Comment by iRayanKhan** [comment] 2019-10-18 05:27
> Found the issue where you can't get fan speed above 67%. It's fixed in [2.3.2](https://github.com/aarons22/homebridge-bond/releases/tag/2.3.2)!

Can confirm this works! Thank you so much for all the effort you've put in we all appreciate it.

**Comment by methnen** [comment] 2019-10-22 19:46
@aarons22 I'm using homebridge-bond version 2.4.0 and with an older Bond Hub that's running the latest v2.9.4 firmware.

The reverse, stop and light toggle functionality is working fine but the fan speed stuff is completely broken.

No matter where I put the fan speed on HomeKit 25% 50%, 75%+ the fan is only ever getting set to it's lowest speed.

This is an older 3 Speed MinkaAire fan.

Happy to provide whatever debug info or whatever else you might need just let me know what you need and how I can get it to you.

**Comment by vdotn** [comment] 2019-12-17 16:00
I’m thinking we can call this resolved. It seems to be working as expected now, including my 6-speed fan.

**Comment by methnen** [comment] 2019-12-17 17:31
Yes, seems to working correctly now with the most recent update.

**Closed** 2019-12-17 18:07 UTC
Labels: bug

**Comment by twentyNoise** [comment] 2020-03-12 05:54
I'm still using an older version because I prefer to just tell Siri to set the Fan to 1, 2, 3, 5 or 6 instead of dealing with percentages. Is this still possible even though HomeKit shows the correct values now? That is, is it still possible to ask Siri to set the Fan to Speed 5 or just 5? etc.? If not, can I request that this be added as a feature?

Thanks!

**Comment by aarons22** [comment] 2020-03-12 11:39
@twentyNoise feel free to open a new issue with the feature request!
