### ISSUE TITLE
Causes Homebridge to Stop Functioning

### ISSUE THREAD

**Issue by mbillow** [aarons22/homebridge-bond#31] opened 2019-09-29 20:08 UTC
**Describe the bug**
Once the platform is included in `config.json`, Homebridge completely stops working; despite not emitting any errors to STDOUT/STDERR or any log files. The application itself reports that it is functioning (displays pairing QR, other plugins send out their initial  requests, etc.), but everything in the Home app displays as "Not Responding." I have tried clearing out the accessory cache and re-adding the Homebridge hub from the Home app to no avail.

**Expected behavior**
Helpful output should be provided to point the user to what is misconfigured or malfunctioning. 

**Log Output**
```
homebridge_1  | [9/29/2019, 2:43:59 PM] [Bond] 0 cached accessories were loaded
homebridge_1  | [9/29/2019, 2:43:59 PM] [Bond] Getting devices...
homebridge_1  | [9/29/2019, 2:43:59 PM] [Bond] 2 devices were found on this Bond.
homebridge_1  | [9/29/2019, 2:43:59 PM] [Bond] Attempting to add 2 devices that were not previously added.
homebridge_1  | [9/29/2019, 2:44:07 PM] [Bond] Adding accessory Living Room CF
homebridge_1  | [9/29/2019, 2:44:07 PM] [Bond] Adding accessory Master Bedroom CF
```

**Information (please complete the following information):**
 - Plugin version: 2.1.0
 - Bond firmware version: v2.8.2
 - iOS version: iOS 13.1 Public beta 4

**Additional context**
 - This is running in the [oznu docker container](https://github.com/oznu/docker-homebridge).
 - The log output leads me to believe that my configuration is correct.
 - I have set both `DEBUG=*` and run homebridge with the `-D` flag, still nothing.
 - I have two fans in Bond, both have the same available buttons: Fan Speeds 1-8, Fan Off, and Summer/Winter directions.

**Comment by aarons22** [comment] 2019-09-29 20:40
It sounds like other users using oznu docker containers have seen similar issues. Your log output does confirm your config is correct.

**Comment by aarons22** [comment] 2019-09-29 20:42
See the comment here: https://github.com/aarons22/homebridge-bond/issues/29#issuecomment-536226117

**Comment by mbillow** [comment] 2019-09-29 21:04
I don’t think there is anything in that thread I haven’t already tried. I can give it a go in the _exact order_, but I don’t think just erase your entire setup and start over is an acceptable solution to this problem in the long term. I can try and dig into this more later, but I have to admit I have been a little to pampered by other things just working so I haven’t really familiarized myself with the inner workings of Homebridge. 😂

**Comment by aarons22** [comment] 2019-09-29 21:26
Yeah I wish I could be more help, I just don’t know if I can spend time replicating your environment to see what’s going on. The other option would be for you to pull down the repo and run it locally, adding some logs throughout to see what’s going on. I’ve being wanting to add more debugging logs, and it sounds like I need to look into the debugging flag provided by homebridge.

**Comment by iRayanKhan** [comment] 2019-09-29 22:03
Schools busy for me, I can try to make a fork to add more than one instance, but I don’t have a spare bond to test. What if you made a new user on your Pi (if you use one) and run an instance of Homebridge on it.

**Comment by vdotn** [comment] 2019-09-30 03:03
@mbillow It’s more of an issue with how the container script handles upgrades. Oznu recommended using packages.json for the longest time. Still might. If you had it dynamically loading via startup.sh, I suspect that just clearing your cache would have been sufficient as it worked for people running homebridge natively (as described in the 1.0 -> 2.0 migration guide).

If you want help digging into it more I can probably help out.

**Comment by aarons22** [comment] 2019-09-30 16:04
Those logs are helpful. It looks like the request to get the state of the device is failing. I’ll add some more debug logs to the next version and hopefully we can isolate the issue!

**Comment by aarons22** [comment] 2019-10-01 17:32
So I think what what happening is the API was throwing an error and in that case, the plugin wasn't responding to HomeKit, in turn causing the "No Response" issue. I've attempted to fixed this in [2.1.1](https://github.com/aarons22/homebridge-bond/releases/tag/2.1.1)

There is likely an API issue that will surface once your update, but I've added some additional logging to help identify what the issue is.

**Comment by aarons22** [comment] 2019-10-02 20:59
I’m currently away from my home and seeing the issue you are describing! This leads me to believe it’s an issue where the Home app is attempting to communicate with the local IP address of the bond. I _thought_ it would funnel the requests through my Apple TV, but apparently that’s not the case.

This also explains why operating this plugin inside a VM might not work if it can’t resolve the IP address.

Anyone have thoughts on how to resolve this? Only thing I can think of off the top of my head is using something like a DNS relay, which increases the complexity of the plugin for a lot of people.

**Comment by mbillow** [comment] 2019-10-02 21:17
I can’t reproduce the issue of it not working remotely. I turned both WiFi and Bluetooth off and was able to control my fans perfectly. Your Apple TV should definitely be doing to heavy lifting in this scenario. I could go as far as to unplug my Apple TV and see if everything stops working. I am still on 2.1.0, just to be clear.

**Comment by aarons22** [comment] 2019-10-02 21:22
It’s possible my homebridge crashed. I don’t know at this point lol

**Comment by vdotn** [comment] 2019-10-02 21:31
Do you also have homepods by any chance, or is your tv still on tvos12? I was having a similar issue remotely when homepods took over as home hubs because they’re still on ios12.

**Comment by iRayanKhan** [comment] 2019-10-02 21:39
I fixed my biggest issue after months with shared users not being able control accessories remotely. While it may not directly be your issue, I fixed it by disabling as many home hubs as possible ‘till the troubled one was identified (Apple TV 4K tvOS 13.0)

**Comment by aarons22** [comment] 2019-10-02 21:43
I recently updated my Apple TV (non-4K) to tvOS 13, but there are a few iOS devices still on 12

**Comment by aarons22** [comment] 2019-10-02 23:06
I think my issue is something wrong with my whole setup. Probably going to clear everything out soon and scratch.

Regardless, this thread has spiraled a bit. @mbilllw - is your issue still happening?

**Comment by apollo316** [comment] 2019-11-09 20:03
I have more information for this thread. It is Homebridge crashing. See attached. Bonddata.map is not a function, it says. If I remove the bond platform from the config.js everything works fine. My config is good, confirmed with jsonlint. My bond works fine by itself, just not within homekit. Bond firmware: 2.9.5. 

![image](https://user-images.githubusercontent.com/29845379/68534374-21765b00-02f1-11ea-86b0-fd93ee0c49fd.png)

**Comment by apollo316** [comment] 2019-11-09 20:16
For added note: My fan is showing in Homekit regardless of the bond platform being there or not. And Homekit thinks it's communicating with the fan just fine when I have the platform removed from the config.json. But when I add the platform I get the above error and it kills homebridge from running. I have reinstalled the bond platform many times and rejiggered the config.json removing and adding [ and { lines to see if it's just exemplified wrong. No luck. Can't seem to figure this one out.

**Comment by apollo316** [comment] 2019-11-09 20:49
Also, I tried homebridge-bond version 2.5.0 and 2.4.0. Homebridge version 0.4.50. NPM 5.6.0. NodeJS 9.9.0.

**Comment by aarons22** [comment] 2019-11-10 18:42
@apollo316 Sounds like there is something going on with the cached data. Can you clear your cache and try again? `rm -rf ~/.homebridge/accessories/cachedAccessories`

**Comment by apollo316** [comment] 2019-11-11 01:01
No luck. I cleared the accessories and rebooted the pi. Still errors out and stops only if the Bond platform is enabled in the config.json. Any other thoughts?

**Comment by aarons22** [comment] 2019-11-11 22:59
Can you add `”debug”: true` to your bond config and paste the logs from startup here?

**Comment by apollo316** [comment] 2019-11-12 17:32
I sure can but where are the logs stored so I can share them? I had debug true when I got that error in the picture above but I'm sure the logs you want have much more detail. I also tried adding a fake second bridge since the error acts like it's looking for an array instead of a function.

**Comment by aarons22** [comment] 2020-01-05 18:01
@apollo316 you can enable debug mode by following instructions [here](https://github.com/aarons22/homebridge-bond#debug-mode). Debug logs will show up in the console. I'm closing this issue since it's old and I'm not sure your issue is related. If you are still getting errors, please open a new issue and provide debug logs!

**Closed by aarons22** 2020-01-05 18:01 UTC
Labels: bug
