### ISSUE TITLE
Speed settings display/function backward

### ISSUE THREAD

**Issue by JT-EOD** [aarons22/homebridge-bond#45] opened 2019-10-22 14:09 UTC
When the Bond is set to fan level ‘3’ (high), HomeKit displays the fan at 33%. When the fan is set to level ‘1’ (low), HomeKit displays the fan at 100%. This is also the behavior of setting the fan within HomeKit; setting the fan to 33% results in high and setting to 100% results in low.

Plugin version: 2.4.0
Bond version: 2.9.2
iOS 13.2 (17B5077a)

**Comment by vdotn** [comment] 2019-10-22 16:43
Are you using homebridge natively or via docker? This was fixed many versions ago, my first thought is if you’re using docker there’s an issue I’ve seen with the container not properly updating plugins on startup.

If it’s native then we’ll have to dig further!

**Comment by aarons22** [comment] 2019-10-22 21:23
Yeah sorry about that, I'm seeing the issue on my end as well. Looks like I introduced this bug in the latest version. I recommend downgrading if you need that functionality right now

**Comment by aarons22** [comment] 2019-10-22 21:29
I just confirmed this worked fine on 2.3.2 (reverted to this on my own setup). I won't have time to dig into this tonight, but I'll get it fixed soon

**Comment by vdotn** [comment] 2019-10-22 21:53
Interesting, maybe it’s my setup that isn’t upgrading correctly then! I don’t have this regreasion. 🤔

**Comment by JT-EOD** [comment] 2019-10-22 21:58
Just to follow up - I just switched over to a docker version of HomeBridge on a Synology NAS. I was running it on a Pi up until that point. Come to think of it, I might have switched over the day your last update dropped.

**Comment by aarons22** [comment] 2019-10-31 00:17
This should be fixed in [2.4.1](https://github.com/aarons22/homebridge-bond/releases/tag/2.4.1)!

**Closed** 2019-11-10 18:35 UTC
Labels: bug
