### ISSUE TITLE
Tower fan (floor standing fan) not supported or not recognized

### ISSUE THREAD

**Issue by johnoldiges** [aarons22/homebridge-bond#114] opened 2020-11-04 03:56 UTC
My tower fan does not respond to commands via homebridge and shows in log as ‘[Tower Fan] CeilingFanAccessory does not have required actions for fan service. (Missing max_speed property)

Is this an issue that can be fixed as most of these fans merely have a command to toggle though preset speeds on the device itself?

**Comment by aarons22** [comment] 2020-11-06 23:56
I believe this is the same issue as https://github.com/aarons22/homebridge-bond/issues/72?

**Comment by johnoldiges** [comment] 2020-11-07 01:03
Appears to be. Somehow missed that in my search. Sorry for the double post. Do you have any eta on when the new increase speed/decrease speed will be added?

**Comment by aarons22** [comment] 2020-11-07 15:15
Actually you can probably help me with this. Can you post your Bond logs here?

**Comment by johnoldiges** [comment] 2020-11-07 22:24
How would one access their bond logs?

**Comment by aarons22** [comment] 2020-11-07 23:59
Depends on how you run homebridge. You using hoobs? Homebridge ui?

**Comment by johnoldiges** [comment] 2020-11-08 00:02
Just running it on a hyper vm in windows

**Comment by aarons22** [comment] 2020-11-08 00:17
Yeah wherever you are running homebridge will have logs. That's where you see the QR code to scan your homebridge into HomeKit when it boots up.

**Comment by johnoldiges** [comment] 2020-11-08 00:41
Ok so you just want me to grab the hombridge logs from the view logs button next to the restart button? Should I turn on debug mode first?

if there is a homebridge_bond plugin specific log I have yet to find it, only the homebridge log with all plugin logs.

**Comment by aarons22** [comment] 2020-11-09 16:33
Yup! bond logs will show up in the home bridge logs with `[Bond]` at the beginning

**Comment by johnoldiges** [comment] 2020-11-09 19:05
Ok, I will upload when I get off work.

Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by johnoldiges** [comment] 2020-11-09 23:35
Ok here is the log.
[homebridge.log.txt](https://github.com/aarons22/homebridge-bond/files/5513849/homebridge.log.txt)

**Comment by aarons22** [comment] 2020-11-10 02:30
Thanks for this! I attempted to add this feature in [3.2.0](https://github.com/aarons22/homebridge-bond/releases/tag/3.2.0). Please validate and let me know how it goes.

**Comment by johnoldiges** [comment] 2020-11-10 02:46
Both features do send the commands to my fane now, but the increase/decrease speed act as another power switch. HomeKit appears to read this as a power switch instead of two independent buttons. When I hit the switch to increase the speed it toggles the switch to an on state then back off causing the bond to shoot off multiple or blasts which results in the Dan moving 2 or more preset speed values. [Video.zip](https://github.com/aarons22/homebridge-bond/files/5514503/Video.zip)

**Comment by johnoldiges** [comment] 2020-11-10 02:51
In short the increase and decrease buttons need to be separate commands like how the reverse button is at the bottom of that window in the video.

**Comment by aarons22** [comment] 2020-12-15 02:26
@johnoldiges yeah, the folks in #72 also reported this issue. Should be fixed in [3.2.1](https://github.com/aarons22/homebridge-bond/releases/tag/3.2.1)!

**Comment by aarons22** [comment] 2020-12-23 20:24
Going to assume this has been addressed since the similar issue has been confirmed as fixed. Closing this now, but feel free to open a new issue (or discussion) if something else isn't working

**Closed by aarons22** 2020-12-23 20:24 UTC
