### ISSUE TITLE
Latest release crashes on startup

### ISSUE THREAD

**Issue by mbriney** [aarons22/homebridge-bond#11] opened 2018-12-04 00:42 UTC
Something has gone wrong with the latest release on my system.  It is possible to post a previous version number?  

```
[2018-12-3 19:37:12] ---
Load homebridge-bond.Bond

/usr/lib/node_modules/homebridge-bond/dist/index.js:10
        let email = config['email'];
                          ^
TypeError: Cannot read property 'email' of null
    at new BondPlatform (/usr/lib/node_modules/homebridge-bond/dist/index.js:10:27)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:347:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by plainsane** [comment] 2018-12-04 05:01
0.1.1 was previous version 
https://www.npmjs.com/package/homebridge-bond/v/0.1.1
What version are you running because this error acts like it can’t read your config correctly

**Comment by iRayanKhan** [comment] 2018-12-04 07:02
Make sure this is installed globally 
~~~
Sudo npm i -g homebridge-bond
~~~

**Comment by iRayanKhan** [comment] 2018-12-05 16:41
And it may help to delete the bond cache since it's what I did

**Comment by mbriney** [comment] 2018-12-05 21:16
How do you delete the cache?

**Comment by miket0429** [comment] 2018-12-17 19:52
I have the same issue with 0.2.0. Coming from 0.1.1 or 0.1.0, everything was fine before trying to upgrade.

**Comment by mbriney** [comment] 2018-12-17 21:41
@miket0429 how did you manually roll it back?  I only see one official release for 0.2.0.

**Comment by plainsane** [comment] 2018-12-29 00:38
This is most likely caused by the reverse switch since I removed it, as it was superfluous after adding a direction characteristic to the fan

**Comment by aarons22** [comment] 2019-09-27 02:12
Closing this as it is no longer applicable with v2 API.

**Closed by aarons22** 2019-09-27 02:12 UTC
