### ISSUE TITLE
Serial Number Error

### ISSUE THREAD

**Issue by Brwndude2160** [aarons22/homebridge-bond#137] opened 2021-02-22 15:29 UTC
**Describe the bug**
Suddenly showed up after the update, the error does not cause issues with the usability of the plugin. just wanted to know if there is anything i or dev can do to fix the error. 

**Information (please complete the following information):**
 - Plugin version 3.2.3
 - Bond firmware version 2.15
 - How homebridge is run:  | Homebridge UI | 
 
**Logs**
[22/02/2021, 10:22:51] [homebridge-bond] This plugin threw an error from the characteristic 'Serial Number': Error: [Serial Number] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory. Ignoring new value.
    at SerialNumber.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:38)
    at SerialNumber.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1257:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at Object.create (/usr/local/lib/node_modules/homebridge-bond/dist/platformAccessory.js:17:14)
    at BondPlatform.create (/usr/local/lib/node_modules/homebridge-bond/dist/platform.js:173:65)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bond/dist/platform.js:155:26)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) See https://git.io/JtMGR for more info.

**Comment by aarons22** [comment] 2021-03-05 23:02
weird, the serial number is set based on the deviceId provided by bond. If you re-boot homebridge does this still happen?

**Comment by KCFT23** [comment] 2021-03-05 23:39
Yes, I can confirm I get the same error.  I have rebooted several times in the last few days and it always comes back.

**Comment by aarons22** [comment] 2021-04-01 01:42
Would you mind providing logs? Preferably in debug mode: https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode

**Comment by Brwndude2160** [comment] 2021-04-01 01:47
Bond Error In Debug mode: 

[31/03/2021, 21:46:14] [homebridge-bond] Error: 
    at SerialNumber.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at SerialNumber.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:16)
    at SerialNumber.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1298:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at Object.create (/usr/local/lib/node_modules/homebridge-bond/dist/platformAccessory.js:17:14)
    at BondPlatform.create (/usr/local/lib/node_modules/homebridge-bond/dist/platform.js:173:65)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bond/dist/platform.js:155:26)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[31/03/2021, 21:46:14] [Bond] Request (185e22c7029d8000) [get http://192.168.1.140/v2/devices/1/state]
[31/03/2021, 21:46:14] [Bond] UDP Message received from 192.168.1.140:30007 - {"B":"KSMWSCE78990"}
[31/03/2021, 21:46:14] [Bond] Response (185e22c7029d8000) [get http://192.168.1.140/v2/devices/1/state] - {"power":0,"speed":2,"light":0,"brightness":100,"brightness_cycle_phase":-1,"timer":0,"breeze":[0,50,50],"direction":1,"_":"e81b5310"}

**Comment by aarons22** [comment] 2021-04-01 03:20
Ahhhh I think I see the issue. Your device id is `1`, which is only 1 character 😄 

This should be fixed in [3.2.6](https://github.com/aarons22/homebridge-bond/releases/tag/3.2.6)

**Comment by aarons22** [comment] 2021-04-08 03:23
I'm going to consider this closed since I was able to replicate the issue and then fix in 3.2.6!

**Closed by aarons22** 2021-04-08 03:23 UTC
Labels: bug
