### ISSUE TITLE
out of sync

### ISSUE THREAD

**Issue by cirrusflyer** [aarons22/homebridge-bond#88] opened 2020-06-09 04:38 UTC
I can't seem to get my fan with two lights to stay in sync.  I'm running the latest version of Bond firmware and latest version of this plugin.  It's the lower light of a two light fan.  I'll have them in sync, but then it seems Homebridge changes the state to on, no matter what the actual state.  I've tried multiple methods using the state fix in the Bond app and using the real remote.

**Comment by cirrusflyer** [comment] 2020-06-09 13:18
Let me add that I had upgraded to latest version, then cleared the device cache so I could see both upper and lower lights.  I just did the same on another fan, and same problem.  Not matter the light state, when returning to the Home app, and after it refreshes, it shows one of the two lights on.  When it is not on.  No matter what.

**Comment by StumbleNOLA** [comment] 2020-06-16 05:15
Thank you so much for this plugin. I wish I had gotten it a year ago!  

Would it be possible to add a ‘sync’ button that would change the state of a fan shown in HomeKit without sending a command to the fan? I have a lot of fans with just a power button for the light, and if they get out of sync I am forced to go scrounge for the remote to get them back in sync.

**Comment by chrismerck** [comment] 2020-06-16 12:40
> a lot of fans with just a power button for the light, and if they get out of sync I am forced to go scrounge for the remote to get them back in sync

From a Bond API perspective, this can be done via PATCH to devices/x/state.light. (That causes Bond to update its state belief without any transmission.)

**Comment by aarons22** [comment] 2020-06-20 21:45
@vdotn can you provide some debugs logs for when your two light fan gets out of sync? would love to see what I'm missing about the state

**Comment by aarons22** [comment] 2020-06-20 21:46
@StumbleNOLA there is a feature request for that here: https://github.com/aarons22/homebridge-bond/issues/75

**Comment by methnen** [comment] 2020-07-11 17:02
I think my issue is somewhat tangentially related to this one. I have a top light showing in HomeKit despite not having one setup in the Bond app. Additionally the bottom light is now completely out of sync with the Bond app. When HomeKit says it's on it's off. The Bond app has it correct though. I've tried fiddling with it to no avail so far. Also on all of the latest versions for everything.

**Comment by aarons22** [comment] 2020-08-30 18:24
This bug should be fixed in the latest version!

**Closed by aarons22** 2020-08-30 18:24 UTC
Labels: bug

**Comment by vdotn** [comment] 2020-08-30 20:36
Confirmed fixed, thanks Aaron! I was actually coming here to dump the logs you asked me fore 2 months ago (sorry!) and noticed I couldn't reproduce anymore haha
